[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [[plugins.inputs.audits]]
    path = ""

  [[plugins.inputs.audits]]
    path = ""
    fileName = "contact.html"

  [[plugins.inputs.audits]]
    path = "about"
    fileName = "something.html"

  [[plugins.inputs.audits]]
    path = "about"



