[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [[plugins.inputs.audits]]
    path = ""

  [[plugins.inputs.audits]]
    path = "contact.html"

  [[plugins.inputs.audits]]
    path = "about/something.html"

  [[plugins.inputs.audits]]
    serveDir = "about"

  [[plugins.inputs.audits]]
    path = "faqs"



