[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs.thresholds]
    performance = 0.9

  [[plugins.inputs.audits]]
    path = ""

  [[plugins.inputs.audits]]
    urlPath = "/about"

  [[plugins.inputs.audits]]
    urlPath = "/contact"

  [[plugins.inputs.audits]]
    urlPath = "/about/something"

  [[plugins.inputs.audits]]
    url = "https://lighthouse-plugin-experiment.netlify.app/something.html"