[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [[plugins.inputs.audits]]
    path = ""

  [[plugins.inputs.audits]]
    path = "contact.html"

  [[plugins.inputs.audits]]
    path = "about/something.html"

  [[plugins.inputs.audits]]
    serveDir = "about"

  [[plugins.inputs.audits]]
    path = "faqs"

  # optional, deploy the lighthouse report to a path under your site
  [plugins.inputs]
    output_path = "reports/lighthouse.html"



